var _ = {};

_.SETTINGS_HEADER_TABLE_SIZE = 0x1;
_.SETTINGS_ENABLE_PUSH = 0x2;
_.SETTINGS_MAX_CONCURRENT_STREAMS = 0x3;
_.SETTINGS_INITIAL_WINDOW_SIZE = 0x4;
_.SETTINGS_MAX_FRAME_SIZE = 0x5;
_.SETTINGS_MAX_HEADER_LIST_SIZE = 0x6;

_.ERROR_NO_ERROR = 0x0;
_.ERROR_PROTOCOL_ERROR = 0x1;
_.ERROR_INTERNAL_ERROR = 0x2;
_.ERROR_FLOW_CONTROL_ERROR = 0x3;
_.ERROR_SETTINGS_TIMEOUT = 0x4;
_.ERROR_STREAM_CLOSED = 0x5;
_.ERROR_FRAME_SIZE_ERROR = 0x6;
_.ERROR_REFUSED_STREAM = 0x7;
_.ERROR_CANCEL = 0x8;
_.ERROR_COMPRESSION_ERROR = 0x9;
_.ERROR_CONNECT_ERROR = 0xa;
_.ERROR_ENHANCE_YOUR_CALM = 0xb;
_.ERROR_INADEQUATE_SECURITY = 0xc;
_.ERROR_HTTP_1_1_REQUIRED = 0xd;

_.ERROR_NAME = [];
_.ERROR_NAME[_.ERROR_NO_ERROR] = 'NO_ERROR';
_.ERROR_NAME[_.ERROR_PROTOCOL_ERROR] = 'PROTOCOL_ERROR';
_.ERROR_NAME[_.ERROR_INTERNAL_ERROR] = 'INTERNAL_ERROR';
_.ERROR_NAME[_.ERROR_FLOW_CONTROL_ERROR] = 'FLOW_CONTROL_ERROR';
_.ERROR_NAME[_.ERROR_SETTINGS_TIMEOUT] = 'SETTINGS_TIMEOUT';
_.ERROR_NAME[_.ERROR_STREAM_CLOSED] = 'STREAM_CLOSED';
_.ERROR_NAME[_.ERROR_FRAME_SIZE_ERROR] = 'FRAME_SIZE_ERROR';
_.ERROR_NAME[_.ERROR_REFUSED_STREAM] = 'REFUSED_STREAM';
_.ERROR_NAME[_.ERROR_CANCEL] = 'CANCEL';
_.ERROR_NAME[_.ERROR_COMPRESSION_ERROR] = 'COMPRESSION_ERROR';
_.ERROR_NAME[_.ERROR_CONNECT_ERROR] = 'CONNECT_ERROR';
_.ERROR_NAME[_.ERROR_ENHANCE_YOUR_CALM] = 'ENHANCE_YOUR_CALM';
_.ERROR_NAME[_.ERROR_INADEQUATE_SECURITY] = 'INADEQUATE_SECURITY';
_.ERROR_NAME[_.ERROR_HTTP_1_1_REQUIRED] = 'HTTP_1_1_REQUIRED';

_.TYPE_DATA = 0x0;
_.TYPE_HEADERS = 0x1;
_.TYPE_PRIORITY = 0x2;
_.TYPE_RST_STREAM = 0x3;
_.TYPE_SETTINGS = 0x4;
_.TYPE_PUSH_PROMISE = 0x5;
_.TYPE_PING = 0x6;
_.TYPE_GOAWAY = 0x7;
_.TYPE_WINDOW_UPDATE = 0x8;
_.TYPE_CONTINUATION = 0x9;

_.FRAME_NAME = [];
_.FRAME_NAME[_.TYPE_DATA] = 'DATA';
_.FRAME_NAME[_.TYPE_HEADERS] = 'HEADERS';
_.FRAME_NAME[_.TYPE_PRIORITY] = 'PRIORITY';
_.FRAME_NAME[_.TYPE_RST_STREAM] = 'RST_STREAM';
_.FRAME_NAME[_.TYPE_SETTINGS] = 'SETTINGS';
_.FRAME_NAME[_.TYPE_PUSH_PROMISE] = 'PUSH_PROMISE';
_.FRAME_NAME[_.TYPE_PING] = 'PING';
_.FRAME_NAME[_.TYPE_GOAWAY] = 'GOAWAY';
_.FRAME_NAME[_.TYPE_WINDOW_UPDATE] = 'WINDOW_UPDATE';
_.FRAME_NAME[_.TYPE_CONTINUATION] = 'CONTINUATION';
_.FRAME_NAME[0xa] = 'ALTSVC (not in RFC)';
_.FRAME_NAME[0xb] = 'BLOCKED (not in RFC)';

module.exports = _;